name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Say hello
      run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - name: Say goodbye
      run: ./goodbye.sh
      shell: bash
    - name: Run reusable workflow
      uses: dtingg/learning-github-actions/actions/reusable
