name: "Reusable composite action"

description: "Run build process"

inputs:
  token:
    description: 'Token for secret stuff'
    required: true
    default: 'grapes'

runs:
  using: "composite"
  steps:
    - name: Start workflow
      run:
        echo Workflow is starting
      shell: bash
    - name: Run processing
      env:
        DIANNA_URL: 'https://http.cat'
        DIANNA_TOKEN: ${{ secrets.DIANNA_TOKEN }}
      run: |
        curl -s -H "Content-Type: application/json" \
        -u "":$DIANNA_TOKEN \
        -X POST ${DIANNA_URL}/202
      shell: bash
    - name: Workflow finished
      run:
        echo Workflow is finished
      shell: bash
