name: "Reusable composite action"
description: "Run build process"
runs:
  using: "composite"
  steps:
    - name: Run processing
      env:
        DIANNA_URL: 'https://http.cat'
        DIANNA_TOKEN: 'goodtoken'
      run: |
        curl -s -H "Content-Type: application/json" \
        -u "":$DIANNA_TOKEN \
        -X POST ${DIANNA_URL}/202
      shell: bash
