name: Reusable workflow example

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run processing
        env:
          DIANNA_URL: 'https://http.cat/202'
          DIANNA_TOKEN: ${{ secrets.DIANNA_TOKEN }}
        run:
          curl -I ${DIANNA_URL}
