name: Reusable workflow example

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  build:
    name: Pass secret to my-action
    runs-on: ubuntu-latest
    steps:
      env:
        DIANNA_URL: 'https://http.cat/202'
        DIANNA_TOKEN: ${{ secrets.DIANNA_TOKEN }}
      run:
        curl -I ${DIANNA_URL}
